- type: playTimeTracker
  id: JobLeaderArrows

- type: playTimeTracker
  id: JobSoldierArrows

- type: playTimeTracker
  id: JobSoldierCCA

- type: playTimeTracker
  id: JobSoldierOTA

- type: playTimeTracker
  id: JobSoldierCCAC