- type: job
  id: MedicalIntern
  name: job-name-intern
  description: job-description-intern
  playTimeTracker: JobMedicalIntern
  requirements:
    # - !type:DepartmentTimeRequirement # Sunrise-edit: disable department time gate for intern role inversion
    #   department: Medical
    #   time: 5h
    #   #inverted: true # stop playing intern if you're good at med! Sunrise-edit
  startingGear: MedicalInternGear
  icon: "JobIconMedicalIntern"
  supervisors: job-supervisors-medicine
  canBeAntag: false
  displayWeight: 0  # Sunrise-Edit
  access:
  - Medical
  - Maintenance

- type: startingGear
  id: MedicalInternGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: MedicalInternPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    pocket2: BookMedicalReferenceBook
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: MedicalInternChameleonOutfit
  job: MedicalIntern
  equipment:
    head: ClothingHeadHatBeretMedic
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatLabOpened
    gloves: ClothingHandsGlovesLatex
