Project-Condor:
  org: space-sunrise
  project: 2
  inbox: Inbox
  labels:
    "W: In Progress": "In Progress"
    "W: Discussion": "Design and Discussion"
    "W: Backlog": "Backlog"
    "W: Next": "Next"
