- type: latheRecipePack
  id: SecurityStaticSunrise
  recipes:
    ######################BOX#######################
    # Light Rifle
    - MagazineBoxLightRifleSP
    - MagazineBoxLightRifleHP
    - MagazineBoxLightRifleFMJ
    # Magnum
    - MagazineBoxMagnumSP
    - MagazineBoxMagnumHP
    - MagazineBoxMagnumFMJ
    - MagazineBoxMagnumRubber
    - MagazineMagnumRubber
    - MagazineMagnum
    - MagazineMagnumFMJ
    - MagazineMagnumHP
    - MagazineMagnumEmpty
    - MagazineMagnumPractice
    # Pistol
    - MagazineBoxPistolSP
    - MagazineBoxPistolHP
    - MagazineBoxPistolFMJ
    - MagazineBoxPistolRubber
    - MagazineBoxPistol40SP
    - MagazineBoxPistol40HP
    - MagazineBoxPistol40FMJ
    # Rifle
    - MagazineBoxRifleSP
    - MagazineBoxRifleHP
    - MagazineBoxRifleFMJ
    # Rifle Heavy
    - MagazineBoxHeavyRifleFMJ
    - MagazineBoxHeavyRifleHP
    - MagazineBoxHeavyRifleSP
    - MagazineBoxHeavyRiflePractice
    # Shotgun
    - BoxLethalshot
    - BoxShotgunSlug
    - BoxShellTranquilizer
    #####################MAGAZINE#######################
    # LMG
    - LightRifleMagazineSP
    - LightRifleMagazineHP
    - LightRifleMagazineFMJ
    - LightRifleMagazineEmpty
    # Light Rifle
    - MagazineLightRifleSP
    - MagazineLightRifleHP
    - MagazineLightRifleFMJ
    - MagazineLightRifleEmpty
    # Magnum
    - SpeedLoaderMagnumSP
    - SpeedLoaderMagnumHP
    - SpeedLoaderMagnumFMJ
    - SpeedLoaderMagnumRubber
    - SpeedLoaderMagnumEmpty
    # Pistol
    - MagazinePistolSP
    - MagazinePistolHP
    - MagazinePistolFMJ
    - MagazinePistolRubber
    - MagazinePistolEmpty
    - MagazinePistol40SP
    - MagazinePistol40HP
    - MagazinePistol40FMJ
    - MagazinePistol40Empty
    # Pistol High Capacity
    - MagazinePistolHighCapacitySP
    - MagazinePistolHighCapacityHP
    - MagazinePistolHighCapacityFMJ
    - MagazinePistolHighCapacityRubber
    - MagazinePistolHighCapacityEmpty
    # SMG
    - MagazinePistolSubMachineGunSP
    - MagazinePistolSubMachineGunHP
    - MagazinePistolSubMachineGunFMJ
    - MagazinePistolSubMachineGunEmpty
    # SMG Top Mounted
    - MagazinePistolSubMachineGunTopMounted # FMJ
    - MagazinePistolSubMachineGunTopMountedSP
    - MagazinePistolSubMachineGunTopMountedHP
    - MagazinePistolSubMachineGunTopMountedEmpty
    # Rifle
    - MagazineRifleSP
    - MagazineRifleHP
    - MagazineRifleFMJ
    - MagazineRifleEmpty
    # Rifle Heavy
    - MagazineRifleHeavyFMJ
    - MagazineRifleHeavyHP
    - MagazineRifleHeavySP
    - MagazineRifleHeavyEmpty
    # Shotgun Magazine
    - MagazineShotgun
    - MagazineShotgunEmpty
    - MagazineShotgunSlug
    # Shotgun Speedloader
    - SpeedLoaderShellShotgun
    - SpeedLoaderShotgunEmpty
    - SpeedLoaderShotgunSlug
    - SpeedLoaderShotgunBeanbag
####################################################

- type: latheRecipePack
  id: SecurityDynamicSunrise
  recipes:
    - WeaponEnergyGun
    - WeaponMiniEnergyGun
    - WeaponEnergyGunPistol
    - WeaponGunLaserCarbineAutomatic
    - MagazineBatteryLr30
    - FlareGunSecurityUpgrade
# Sunrise-TODO: Нужен ребаланс с учетом типов боеприпасов
#    - BaseMagazinePistolCaselessRifleExtended
#    - MagazinePPSH41Extended
#    - MagazineMP5Extended
#    - MagazineMP7Extended
#    - MagazineRifleExtended
#    - MagazineAR18Extended
#    - MagazineM28Extended
#    - MagazineV31Extended
#   - MagazineBauer127Extended
#    - MagazineBR64Extended
#    - MagazineDragunovExtended
    - ShellBlastArtillery
    - ShellEMPArtillery
    - ShellFlashArtillery
    - EnergyDomeDirectionalTurtle
    - WeaponTemperatureGun
    - ModularReceiverAuto
    - LecterUpgrade
    - DrozdUpgrade
  #####################BOX#######################
  # Light Rifle
    - MagazineBoxLightRifleIncendiary
    - MagazineBoxLightRifleUranium
    - MagazineBoxLightRifleAP
  # Magnum
    - MagazineBoxMagnumIncendiary
    - MagazineBoxMagnumUranium
    - MagazineBoxMagnumAP
  # Pistol
    - MagazineBoxPistolIncendiary
    - MagazineBoxPistolUranium
    - MagazineBoxPistolAP
    - MagazineBoxPistol40AP
  # Rifle
    - MagazineBoxRifleIncendiary
    - MagazineBoxRifleUranium
    - MagazineBoxRifleAP
  # Heavy Rifle
    - MagazineBoxHeavyRifleAP
    - MagazineBoxHeavyRifleIncendiary
    - MagazineBoxHeavyRifleUranium
  # Shotgun
    - BoxBeanbag
    - BoxShotgunIncendiary
    - BoxShotgunUranium
    - BoxShellTranquilizer
  #####################MAGAZINE#######################
  # LMG
    - LightRifleMagazineIncendiary
    - LightRifleMagazineUranium
    - LightRifleMagazineAP
  # Light Rifle
    - MagazineLightRifleIncendiary
    - MagazineLightRifleUranium
    - MagazineLightRifleAP
  # Magnum
    - SpeedLoaderMagnumIncendiary
    - SpeedLoaderMagnumUranium
    - SpeedLoaderMagnumAP
    - MagazineMagnumUranium
    - MagazineMagnumAP
  # Pistol
    - MagazinePistolIncendiary
    - MagazinePistolUranium
    - MagazinePistolAP
    - MagazinePistol40AP
  # Pistol High Capacity
    - MagazinePistolHighCapacityIncendiary
    - MagazinePistolHighCapacityUranium
    - MagazinePistolHighCapacityAP
  # SMG
    - MagazinePistolSubMachineGunIncendiary
    - MagazinePistolSubMachineGunUranium
    - MagazinePistolSubMachineGunAP
    - MagazinePistolSubMachineGunRubber
    # SMG Top Mounted
    - MagazinePistolSubMachineGunTopMountedAP
    - MagazinePistolSubMachineGunTopMountedIncendiary
    - MagazinePistolSubMachineGunTopMountedUranium
    - MagazinePistolSubMachineGunTopMountedRubber
  # Rifle
    - MagazineRifleIncendiary
    - MagazineRifleUranium
    - MagazineRifleAP
  # Rifle Heavy
    - MagazineRifleHeavyIncendiary
    - MagazineRifleHeavyAP
    - MagazineRifleHeavyUranium
  # Shotgun
    - MagazineShotgunBeanbag
    - MagazineShotgunIncendiary
    - SpeedLoaderShotgunIncendiary
    - SpeedLoaderShotgunUranium
  # Grenade
    - MagazineGrenadeEmpty
####################################################

- type: latheRecipePack
  id: SecurityDynamicSunriseClothing
  recipes:
    - ClothingHeadHelmetPubg
    - ClothingShoesBootsMagSec
    - ClothingShoesBootsMagCombat
    - VestSecUpgradePlate
    - VestSecUpgradeStab
    - VestSecUpgradeHeat
    - VestSecUpgradeBullet
    - VestSecUpgradeRiot
    - VestSecUpgradeReflective
    - VestSecUpgradeWeb
    - VestSecUpgradeBulletHeavy

- type: latheRecipePack
  id: SecurityDynamicSunriseMech
  recipes:
    - WeaponMechCombatImmolationGun
    - WeaponMechCombatSolarisLaser
    - WeaponMechCombatFiredartLaser
    - WeaponMechCombatUltraRifle
    - WeaponMechCombatMG
    - WeaponMechCombatIon
    - WeaponMechCombatXray
    - WeaponMechCombatShotgun
    - WeaponMechCombatShotgunIncendiary
    - WeaponMechCombatDisabler
    - WeaponMechCombatFlashbangLauncher
    - WeaponMechCombatMissileRack8
