#Fish-edit
# - type: department
#   id: Law
#   name: department-Law
#   description: department-Law-description
#   color: "#FF5297"
#   weight: 80
#   roles:
    #  - Magistrat
    #  - IAA
    #  - Lawyer
    #  - NtrOfficer
#Fish-end

# - type: department # Surnise-Blueshield
#   id: BlueShield
#   name: department-Blueshield
#   description: department-Blueshield-description
#   color: "#0f4e81"
#   roles:
# - type: department # Surnise-Blueshield
#   id: BlueShield
#   name: department-Blueshield
#   description: department-Blueshield-description
#   color: "#0f4e81"
#   roles:
#    - BlueShieldEnsign
#    - BlueShieldOfficer
#    - BlueShieldOperative
#   primary: false
#   weight: 50
#   primary: false
#   weight: 50

- type: department
  id: PlanetPrison
  sort: 0
  name: department-PlanetPrison
  description: department-PlanetPrison-description
  color: "#9f4000"
  roles:
  - HeadOfPrison
  - PrisonWorker
  - PrisonChef
  - PrisonDoctor
  - PrisonEngineer
  - PrisonGuard
  - PlanetPrisoner

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#0d4f1d"
  roles:
  # - CentCommOperator #Fish-edit
  # - CentCommOperator #Fish-edit
  - CentCommOfficial
  - CentCommHead #Fish-edit
  - CentCommOfficer #Fish-edit
  - CentCommTrainee #Fish-edit
  - CentcommBlueShield #Fish-edit
  - CentcommChef #Fish-edit
  - CentcommMedicalDoctor #Fish-edit
  - CentcommBartender #Fish-edit
  weight: 120

- type: department
  id: SpecialOperations
  name: department-SpecialOperations
  description: department-SpecialOperations-description
  color: "#0c344d"
  roles:
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  editorHidden: true
