# Neck

- type: loadout
  id: PlanetPrisonSecurityMasterHandheldCamera
  effects:
  - !type:JobRequirementLoadoutEffect
    requirement:
      !type:DepartmentTimeRequirement
      department: PlanetPrisonSecurity
      time: 108000 # 30 hrs
  inhand:
  - MasterHandheldCamera
