- type: startingGear
  id: SyndicateCorpseGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    shoes: ClothingShoesBootsCombat
    pocket1: SyndicateBusinessCard
    pocket2: Telecrystal1

- type: startingGear
  id: NukieCorpseGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    shoes: ClothingShoesBootsCombat
    head: ClothingHeadHelmetHardsuitSyndie
    outerClothing: ClothingOuterHardsuitSyndieBiocode
    pocket1: WeaponPistolViper
    pocket2: Telecrystal1

# region USSP
- type: startingGear
  id: SovietCorpseGearA
  equipment:
    head: ClothingHeadHatUshanka
    jumpsuit: ClothingUniformJumpsuitAdidasWhite
    shoes: ClothingShoesUSSPBlack
    outerClothing: ClothingOuterWinterCoat
    neck: ClothingNeckUSSPPin
    pocket1: DrinkShotGlass
    gloves: ClothingHandsGlovesFingerless

- type: startingGear
  id: SovietCorpseGearB
  equipment:
    head: ClothingHeadHatBrownFlatcap
    jumpsuit: ClothingUniformJumpsuitAdidasBlack
    shoes: ClothingShoesBootsWinter
    outerClothing: ClothingOuterCoatTrench
    neck: ClothingNeckUSSPPin
    pocket1: DrinkVodkaBottleFull
    gloves: ClothingHandsGlovesFingerless

- type: startingGear
  id: SovietCorpseGearC
  equipment:
    head: ClothingHeadHatGreyFlatcap
    jumpsuit: ClothingUniformJumpsuitAdidasWhite
    shoes: ClothingShoesBootsWinter
    outerClothing: ClothingOuterCoatGentle
    neck: ClothingNeckUSSPPin
    pocket1: SpeedLoaderHeavyRifleRFMJ
    gloves: ClothingHandsGlovesFingerless

- type: startingGear
  id: SovietCorpseGearD
  equipment:
    head: ClothingHeadHatUshanka
    jumpsuit: ClothingUniformJumpsuitAdidasWhite
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterCoatGentle
    neck: ClothingNeckUSSPPin
    pocket1: MagazinePistolSubMachineGunEmpty
    gloves: ClothingHandsGlovesFingerless
  inhand:
  - WeaponSubMachineGunMP38

- type: startingGear
  id: SovietCorpseGearF
  equipment:
    head: ClothingHeadHatGreyFlatcap
    jumpsuit: ClothingUniformJumpsuitAdidasWhite
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterCoatGentle
    neck: ClothingNeckUSSPPin
    pocket1: SpeedLoaderHeavyRifleRFMJ
    gloves: ClothingHandsGlovesFingerless
  inhand:
  - WeaponSniperMosin

- type: startingGear
  id: SovietCorpseGearMarine
  equipment:
    head: ClothingHeadHatBeretAtmos
    jumpsuit: ClothingUSSPMarine
    shoes: ClothingShoesBootsCombatFilled
    pocket1: CigPackSyndicate
    gloves: ClothingHandsGlovesFingerless

- type: startingGear
  id: SovietCorpseGearMarineB
  equipment:
    head: ClothingHeadHatBeretAtmos
    jumpsuit: ClothingUSSPMarine
    shoes: ClothingShoesBootsCombatFilled
    belt: ClothingBeltSalvageWebbing
    pocket1: CigPackSyndicate
    gloves: ClothingHandsGlovesFingerless

- type: startingGear
  id: SovietCorpseGearMarineC
  equipment:
    head: ClothingHeadHatBeretAtmos
    jumpsuit: ClothingUSSPMarine
    outerClothing: ClothingOuterArmorBasicSlim
    shoes: ClothingShoesBootsCombatFilled
    pocket1: CigPackSyndicate
    gloves: ClothingHandsGlovesMercFingerless

- type: startingGear
  id: SovietCorpseGearMarineD
  equipment:
    head: ClothingHeadHatBeretAtmos
    jumpsuit: ClothingUSSPMarine
    shoes: ClothingShoesBootsCombatFilled
    pocket1: MagazineLightRifleEmpty
    gloves: ClothingHandsGlovesMercFingerless
    belt: TrashBagAmmo
  inhand:
  - WeaponRifleSKM24Green

- type: startingGear
  id: SovietCorpseGearMarineF
  equipment:
    head: ClothingHeadHatBeretAtmos
    jumpsuit: ClothingUSSPMarine
    outerClothing: ClothingOuterWinterHoSUnarmored
    shoes: ClothingShoesBootsCombatFilled
    pocket1: MagazineLightRifleEmpty
    gloves: ClothingHandsGlovesMercFingerless
  inhand:
  - WeaponRifleSKM24

- type: startingGear
  id: SovietCorpseGearOfficer
  equipment:
    head: ClothingHeadHatCapUSSPBlack
    jumpsuit: ClothingUniformJumpsuitUSSPBlack
    shoes: ClothingShoesBootsCombatFilled
    outerClothing: ClothingOuterCoatHOSOvercoatBlack
    eyes: ClothingEyesGlassesNoir
    belt: ClothingBeltSecurityFilled
    neck: ClothingNeckUSSPPin
    gloves: ClothingHandsGlovesFingerless

- type: startingGear
  id: SovietCorpseGearOfficerB
  equipment:
    head: ClothingHeadHelmetPubg
    jumpsuit: ClothingUniformJumpsuitUSSPBlack
    shoes: ClothingShoesBootsMerc
    outerClothing: ClothingOuterArmorBulletproofHeavy
    belt: ClothingBeltSalvageWebbing
    neck: ClothingNeckUSSPPin
    gloves: ClothingHandsGlovesFingerless

- type: startingGear
  id: SovietCorpseGearEVALight
  equipment:
    head: ClothingHeadHatBeretAtmos
    jumpsuit: ClothingUSSPMarine
    shoes: ClothingShoesBootsMagPirate
    outerClothing: ClothingOuterLightHardsuitUSSP
    mask: ClothingMaskGasMerc
    pocket1: WeaponLaserSvalinn

- type: startingGear
  id: SovietCorpseGearEVALightB
  equipment:
    head: ClothingHeadHelmetLightHardsuitUSSP
    jumpsuit: ClothingUSSPMarine
    shoes: ClothingShoesBootsMagPirate
    outerClothing: ClothingOuterLightHardsuitUSSP
    mask: ClothingMaskGasMerc
    pocket1: WeaponLaserSvalinn

- type: startingGear
  id: SovietCorpseGearEVA
  equipment:
    head: ClothingHeadHatBeretAtmos
    jumpsuit: ClothingUSSPMarine
    shoes: ClothingShoesBootsCombatFilled
    outerClothing: ClothingOuterHeavyHardsuitUSSP
    mask: ClothingMaskGasMerc
    belt: TrashBagAmmo
    pocket1: MagazineLightRifleMaxim

- type: startingGear
  id: SovietCorpseGearEVAOfficer
  equipment:
    head: ClothingHeadHatCapHoS
    ears: ClothingHeadsetAltUSSP
    jumpsuit: ClothingUniformJumpsuitExplorer
    shoes: ClothingShoesBootsCombatFilled
    outerClothing: ClothingOuterHeavyHardsuitUSSP
    neck: ClothingNeckCloakWhite
    mask: ClothingMaskGasMerc
    pocket1: WeaponRevolverPython

- type: startingGear
  id: MercenaryCorpseGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMercenary
    shoes: ClothingShoesBootsMerc

- type: startingGear
  id: PirateCorpseGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPirate
    outerClothing: ClothingOuterCoatPirate
    pocket1: TreasureCoinGold
