- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 18000 #5 hrs
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 9000 #2.5 hrs
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 36000 #10 hours
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  canBeAntag: true # Sunrise-Edit
  radioBold: true # Sunrise-Edit
  displayWeight: 40  # Sunrise-Edit
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Command
  - Brig
  - Cryogenics
  special:
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  speciesBlacklist:
  - Vox # Sunrise-Edit

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
#    belt: BoxFolderClipboard # Sunrise-Edit
    pocket1: AppraisalTool
  storage:
    back:
    - Flash
