- type: job
  id: DeathSquad
  name: job-name-deathsquad
  description: job-description-deathsquad
  playTimeTracker: JobDeathSquad
  setPreference: false
  startingGear: DeathSquadGear
  icon: "JobIconDeathsquad" # Sunrise-edit
  overrideConsoleVisibility: false # Sunrise added
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: DeathSquadGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingDeathSquadronBackpack # Sunrise-edit
    mask: ClothingMaskGasDeathSquad
    eyes: ClothingEyesHudSecurity
    ears: ClothingHeadsetAltCentCom
    # gloves: ClothingHandsGlovesCombat # Sunrise-edit
    outerClothing: ClothingOuterHardsuitDeathsquad
    shoes: ClothingShoesBootsMagAdv
    id: DeathsquadPDA
    pocket1: PouchAmmo # Sunrise-edit
    pocket2: DoubleEmergencyOxygenTankFilled # Sunrise-edit
    belt: ClothingBeltMedicalElite # Sunrise-edit
  storage:
    back:
    - WeaponPulsePistol
    - WeaponRevolverMatebaAP
    - SpeedLoaderMagnumAP
    - SpeedLoaderMagnumAP
    - BoxFlashbang
    - ToolDebug # spanish army knife
    - WelderExperimental
    # - Hypospray # Sunrise-edit
    - DeathAcidifierImplanter # crew will try to steal their amazing hardsuits
    - FreedomImplanter
    # Sunrise-start
    - EnergySword
    - EnergyShield
    - SpeedLoaderMagnumAP
    - SpeedLoaderMagnumAP
    - BoxErtBaseKit
    # Sunrise-end
  inhand:
  - ClothingHandsPowerGlovesUplinkNTERTEpsilon # Sunrise-edit

- type: chameleonOutfit
  id: DeathSquadChameleonOutfit
  job: DeathSquad
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitDeathsquad
    neck: ClothingNeckBronzeheart
