# Leader
- type: job
  id: ERTLeader
  name: job-name-ertleader
  description: job-description-ertleader
  playTimeTracker: JobERTLeader
  setPreference: false
  startingGear: ERTLeaderGearEVA
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false # Sunrise added
  supervisors: job-supervisors-centcom
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 18000 # 5 hours
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 18000 # 5 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 18000 # 5 hours
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: ERTLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetERTLeader
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolN1984
    pocket2: FlashlightSeclite
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CrowbarRed
    - MagazineMagnum

- type: startingGear
  id: ERTLeaderGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagAdv
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolN1984
    pocket2: FlashlightSeclite
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CrowbarRed
    - MagazineMagnum

- type: startingGear
  id: ERTLeaderGearEVALecter
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagAdv
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: MagazineRifleSP
    pocket2: MagazineRifleIncendiary
  inhand:
  - WeaponRifleLecter
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CrowbarRed
    - MagazineMagnum

- type: chameleonOutfit
  id: ERTLeaderChameleonOutfit
  job: ERTLeader
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTLeader
    neck: ClothingNeckBronzeheart

# Chaplain
- type: job
  id: ERTChaplain
  name: job-name-ertchaplain
  description: job-description-ertchaplain
  playTimeTracker: JobERTChaplain
  setPreference: false
  startingGear: ERTChaplainGear
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false # Sunrise added
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: ERTChaplainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesLeather
    head: ClothingHeadHatFez
    eyes: ClothingEyesGlasses
    neck: ClothingNeckStoleChaplain
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltStorageWaistbag
    pocket1: Flare
    pocket2: DrinkWaterBottleFull
  storage:
    back:
    - BoxCandle
    - BoxBodyBag
    - DrinkWaterMelonJuiceJug
    - Lantern
    - Lantern
    - Bible
    - CrowbarRed
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - Lighter

- type: startingGear
  id: ERTChaplainGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsMagAdv
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlasses
    neck: ClothingNeckStoleChaplain
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTChaplain
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltStorageWaistbag
    pocket1: Flare
    pocket2: DrinkWaterBottleFull
  storage:
    back:
    - BoxCandle
    - BoxBodyBag
    - DrinkWaterMelonJuiceJug
    - Lantern
    - Lantern
    - Bible
    - CrowbarRed
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - Lighter

- type: chameleonOutfit
  id: ERTChaplainChameleonOutfit
  job: ERTChaplain
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTChaplain
    mask: ClothingMaskGasERT
    outerClothing: ClothingOuterHardsuitERTChaplain
    shoes: ClothingShoesBootsMagAdv

# Engineer
- type: job
  id: ERTEngineer
  name: job-name-ertengineer
  description: job-description-ertengineer
  playTimeTracker: JobERTEngineer
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false # Sunrise added
  supervisors: job-supervisors-centcom
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 # 5 hours
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 # 10 hours
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: ERTEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsWork
    head: ClothingHeadHelmetERTEngineer
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltChiefEngineerFilled
    pocket1: Flare
    pocket2: GasAnalyzer
  storage:
    back:
    - trayScanner
    - RCD
    - RCDAmmo
    - RCDAmmo
    - CableMVStack
    - CableHVStack
    - CableApcStack
    - SheetPlasteel
    - SheetSteel
    - SheetGlass

- type: startingGear
  id: ERTEngineerGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMagAdv
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTEngineer
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltChiefEngineerFilled
    pocket1: Flare
    pocket2: GasAnalyzer
  storage:
    back:
    - trayScanner
    - RCD
    - RCDAmmo
    - RCDAmmo
    - CableMVStack
    - CableHVStack
    - CableApcStack
    - SheetPlasteel
    - SheetSteel
    - SheetGlass

- type: chameleonOutfit
  id: ERTEngineerChameleonOutfit
  job: ERTEngineer
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTEngineer
    neck: ClothingNeckEngineermedal

# Security
- type: job
  id: ERTSecurity
  name: job-name-ertsecurity
  description: job-description-ertsecurity
  playTimeTracker: JobERTSecurity
  setPreference: false
  startingGear: ERTSecurityGearEVA
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false # Sunrise added
  supervisors: job-supervisors-centcom
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 # 5 hours
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: ERTSecurityGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetERTSecurity
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58
    pocket2: FlashlightSeclite
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CrowbarRed
    - MagazinePistol

- type: startingGear
  id: ERTSecurityGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58
    pocket2: FlashlightSeclite
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CrowbarRed
    - MagazinePistol

- type: startingGear
  id: ERTSecurityGearEVALecter
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    pocket1: MagazineRifleFMJ #Sunrise-Edit
    pocket2: MagazineRifleFMJ #Sunrise-Edit
  inhand:
   - WeaponRifleLecter
  storage:
    back:
    - WeaponDisabler
    - MedicatedSuture
    - RegenerativeMesh
    - BoxZiptie
    - CrowbarRed
    - MagazinePistol

- type: chameleonOutfit
  id: ERTSecurityChameleonOutfit
  job: ERTSecurity
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTSecurity
    neck: ClothingNeckSecuritymedal

# Medical
- type: job
  id: ERTMedical
  name: job-name-ertmedic
  description: job-description-ertmedic
  playTimeTracker: JobERTMedical
  setPreference: false
  startingGear: ERTMedicalGearEVA
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false # Sunrise added
  supervisors: job-supervisors-centcom
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 # 5 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hours
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: ERTMedicalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHelmetERTMedic
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMedicalFilled
    pocket1: Flare
  storage:
    back:
    - Hypospray
    - MedkitCombatFilled
    - MedkitCombatFilled
    - CrowbarRed
    - ChemistryBottleOmnizine
    - ChemistryBottleEpinephrine
    - ChemistryBottleEpinephrine

- type: startingGear
  id: ERTMedicalGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterHardsuitERTMedical
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMedicalFilled
    pocket1: Flare
  storage:
    back:
    - Hypospray
    - MedkitCombatFilled
    - MedkitCombatFilled
    - CrowbarRed
    - ChemistryBottleOmnizine
    - ChemistryBottleEpinephrine
    - ChemistryBottleEpinephrine

- type: chameleonOutfit
  id: ERTMedicalChameleonOutfit
  job: ERTMedical
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTMedical
    neck: ClothingNeckStethoscope

# Janitor
- type: job
  id: ERTJanitor
  name: job-name-ertjanitor
  description: job-description-ertjanitor
  playTimeTracker: JobERTJanitor
  setPreference: false
  startingGear: ERTJanitorGearEVA
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false # Sunrise added
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: ERTJanitorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHelmetERTJanitor
    gloves: ClothingHandsGlovesColorPurple
    outerClothing: ClothingOuterArmorBasicSlim
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltJanitorFilled
    pocket1: Flare
  storage:
    back:
    - LightReplacer
    - BoxLightMixed
    - BoxLightMixed
    - Soap
    - CrowbarRed
    - AdvMopItem

- type: startingGear
  id: ERTJanitorGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    gloves: ClothingHandsGlovesColorPurple
    outerClothing: ClothingOuterHardsuitERTJanitor
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltJanitorFilled
    pocket1: Flare
  storage:
    back:
    - LightReplacer
    - BoxLightMixed
    - BoxLightMixed
    - Soap
    - CrowbarRed
    - AdvMopItem

- type: chameleonOutfit
  id: ERTJanitorChameleonOutfit
  job: ERTJanitor
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTJanitor
    neck: ClothingNeckScarfStripedPurple
    eyes: ClothingEyesGlassesSunglasses

# --- VETERAN VARIANTS (Strict requirements, for admin/event use) ---
# Sunrise start
- type: job
  id: ERTLeaderVeteran
  name: job-name-ertleader-veteran
  description: job-description-ertleader-veteran
  playTimeTracker: JobERTLeaderVeteran
  setPreference: false
  startingGear: ERTLeaderGearEVA
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false # Sunrise added
  supervisors: job-supervisors-centcom
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 180000 # 50 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 72000 # 20 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 # 10 hours
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: job
  id: ERTChaplainVeteran
  name: job-name-ertchaplain-veteran
  description: job-description-ertchaplain-veteran
  playTimeTracker: JobERTChaplainVeteran
  setPreference: false
  startingGear: ERTChaplainGear
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false # Sunrise added
  supervisors: job-supervisors-centcom
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 90000 # 25 hours
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: job
  id: ERTEngineerVeteran
  name: job-name-ertengineer-veteran
  description: job-description-ertengineer-veteran
  playTimeTracker: JobERTEngineerVeteran
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false # Sunrise added
  supervisors: job-supervisors-centcom
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 180000 # 50 hours
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 90000 # 25 hours
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: job
  id: ERTSecurityVeteran
  name: job-name-ertsecurity-veteran
  description: job-description-ertsecurity-veteran
  playTimeTracker: JobERTSecurityVeteran
  setPreference: false
  startingGear: ERTSecurityGearEVA
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false # Sunrise added
  supervisors: job-supervisors-centcom
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 180000 # 50 hours
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: job
  id: ERTMedicalVeteran
  name: job-name-ertmedic-veteran
  description: job-description-ertmedic-veteran
  playTimeTracker: JobERTMedicalVeteran
  setPreference: false
  startingGear: ERTMedicalGearEVA
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false # Sunrise added
  supervisors: job-supervisors-centcom
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 180000 # 50 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 90000 # 25 hours
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: job
  id: ERTJanitorVeteran
  name: job-name-ertjanitor-veteran
  description: job-description-ertjanitor-veteran
  playTimeTracker: JobERTJanitorVeteran
  setPreference: false
  startingGear: ERTJanitorGearEVA
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false # Sunrise added
  supervisors: job-supervisors-centcom
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 90000 # 25 hours
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: job
  id: CBURNVeteran
  name: job-name-cburn-veteran
  description: job-description-cburn-veteran
  playTimeTracker: JobCBURNVeteran
  setPreference: false
  startingGear: CBURNGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 180000 # 50 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 # 10 hours
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]
# Sunrise end

