- type: entity
  id: CrateServicePrinterDoc
  parent: CrateGenericSteel
  name: printer machine crate
  description:
  components:
  - type: StorageFill
    contents:
    - id: Screwdriver
    - id: PrinterDocFlatpack

- type: entity
  id: CrateServicePrinterDocRestock
  parent: CrateGenericSteel
  name: printer machine restock crate
  description: printer paper with ink and office papper
  components:
  - type: StorageFill
    contents:
    - id: SheetOfficePaper
      amount: 1
    - id: DrinkInc
      amount: 1
