- type: job
  id: MiningSpecialist
  name: job-name-miningspec
  description: job-description-miningspec
  playTimeTracker: JobMiningSpecialist
  requirements:
  - !type:DepartmentTimeRequirement
    department: Cargo
    time: 10800 # 3 hrs
  - !type:OverallPlaytimeRequirement
    time: 36000 #10 hrs
  icon: "JobIconMiner"
  startingGear: MiningSpecialistGear
  supervisors: job-supervisors-qm
  canBeAntag: false #Работать а не антажить!
  access:
  - Cargo
  - Salvage
  - Mining
  - Maintenance
  - External

- type: startingGear
  id: MiningSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMiningSpecialist
    id: MiningPDA
    ears: ClothingHeadsetMining
    belt: OreBag
    head: ClothingHeadHatHardhatYellowDark
    pocket1: MineralScannerUnpowered
    pocket2: EnergyPickaxe

- type: chameleonOutfit
  id: MiningSpecialistChameleonOutfit
  job: MiningSpecialist
  equipment:
    mask: ClothingMaskGas
    outerClothing: ClothingOuterWinterMiner
