- type: job
  id: PrisonDoctor
  name: job-name-prison-doctor
  description: job-description-prison-doctor
  playTimeTracker: JobPrisonDoctor
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 7200 # 2 hrs
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 7200 #2 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200 # 2 hrs
  weight: 6
  alwaysUseSpawner: true
  canBeAntag: false
  startingGear: PrisonDoctorGear
  icon: "JobIconPrisonDoctor"
  overrideConsoleVisibility: false
  supervisors: job-supervisors-head-of-prison
  displayWeight: 50
  access:
  - Security
  - Brig
  - Maintenance
  - Medical
  - Chemistry
  - Paramedic
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: PrisonDoctorGear
  equipment:
    id: PrisonDoctorPDA
    ears: ClothingHeadsetSecurity
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorRiot
    belt: ClothingBeltPrisonDoctorMetus
    back: ClothingBackpackSatchelPrisonDoctorMetus
    shoes: ClothingShoesBootsJack
    pocket1: WeaponPistolG22Prison
    pocket2: SecurityWhistle

- type: chameleonOutfit
  id: PrisonDoctorChameleonOutfit
  job: PrisonDoctor
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisonDoctor
    head: ClothingHeadHatBeretPrisonDoctor
    ears: ClothingHeadsetMedical
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorRiot
    belt: ClothingBeltPrisonDoctorMetus
    back: ClothingBackpackSatchelPrisonDoctorMetus
    shoes: ClothingShoesBootsJack
