- type: job
  id: PrisonScientist
  name: job-name-prison-scientist
  description: job-description-prison-scientist
  playTimeTracker: JobPrisonScientist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 7200 # 2 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200 # 2 hrs
  alwaysUseSpawner: true
  canBeAntag: false
  startingGear: PrisonScientistGear
  icon: "JobIconPrisonScientist"
  overrideConsoleVisibility: false
  supervisors: job-supervisors-head-of-prison
  displayWeight: 60
  access:
    - Security
    - Brig
    - Maintenance
    - Research
    - Medical
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]

- type: startingGear
  id: PrisonScientistGear
  equipment:
    id: PrisonScientistPDA
    jumpsuit: UniformPrisonScientistMetus
    ears: ClothingHeadsetScience
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasic
    belt: ClothingBeltPrisonScientistMetus
    back: ClothingBackpackSatchelPrisonScientistMetus
    shoes: ClothingShoesBootsJack
    pocket1: WeaponPistolG22Metus
    pocket2: SecurityWhistle

- type: chameleonOutfit
  id: PrisonScientistChameleonOutfit
  job: PrisonScientist
  equipment:
    jumpsuit: UniformPrisonScientistMetus
    head: ClothingHeadHatCapPrisonScientistMetus
    ears: ClothingHeadsetScience
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasic
    belt: ClothingBeltPrisonScientistMetus
    back: ClothingBackpackSatchelPrisonScientistMetus
    shoes: ClothingShoesBootsJack
