- type: job
  id: PrisonEngineer
  name: job-name-prison-engineer
  description: job-description-prison-engineer
  playTimeTracker: JobPrisonEngineer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 7200 # 2 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200 # 2 hrs
  weight: 7
  alwaysUseSpawner: true
  canBeAntag: false
  startingGear: PrisonEngineerGear
  icon: "JobIconPrisonEngineer"
  overrideConsoleVisibility: false
  supervisors: job-supervisors-head-of-prison
  displayWeight: 70
  access:
  - Security
  - Brig
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  - Medical
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: PrisonEngineerGear
  equipment:
    ears: ClothingHeadsetJEngineering
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasic
    belt: ClothingBeltPrisonEngineerMetus
    back: ClothingBackpackSatchelPrisonEngineerMetus
    shoes: ClothingShoesBootsJack
    pocket1: WeaponPistolG22Prison
    pocket2: SecurityWhistle

- type: chameleonOutfit
  id: PrisonEngineerChameleonOutfit
  job: PrisonEngineer
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisonEngineer
    head: ClothingHeadHatCapPrisonEngineer
    ears: ClothingHeadsetJEngineering
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBasic
    belt: ClothingBeltPrisonEngineerMetus
    back: ClothingBackpackSatchelPrisonEngineerMetus
    shoes: ClothingShoesBootsJack
