- type: job
  id: PrisonChef
  name: job-name-prison-chef
  description: job-description-prison-chef
  playTimeTracker: JobPrisonChef
  requirements:
    - !type:RoleTimeRequirement
      role: JobChef
      time: 7200 #2 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 7200 # 2 hrs
  icon: "JobIconPrisonChef"
  startingGear: PrisonChefGear
  overrideConsoleVisibility: false
  supervisors: job-supervisors-head-of-prison
  alwaysUseSpawner: true
  canBeAntag: false
  displayWeight: 40
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Kitchen
  - Hydroponics
  - Bar
  - Medical
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: PrisonChefGear
  equipment:
    id: PrisonChefPDA
    jumpsuit: UniformPrisonChefMetus
    ears: ClothingHeadsetService
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskItalianMoustache
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorRiot
    belt: ClothingBeltPrisonChefMetus
    back: ClothingBackpackSatchelPrisonChefMetus
    shoes: ClothingShoesBootsJack
    pocket1: WeaponPistolG22Metus
    pocket2: SecurityWhistle

- type: chameleonOutfit
  id: PrisonChefChameleonOutfit
  job: PrisonChef
  equipment:
    jumpsuit: UniformPrisonChefMetus
    head: ClothingHeadHatChefBlackToque
    ears: ClothingHeadsetService
    eyes: ClothingEyesGlassesSunglasses
    mask: ClothingMaskItalianMoustache
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorRiot
    belt: ClothingBeltPrisonChefMetus
    back: ClothingBackpackSatchelPrisonChefMetus
    shoes: ClothingShoesBootsJack
