- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
  - !type:RoleTimeRequirement
    role: JobScientist
    time: 18000 #5 hrs
  - !type:DepartmentTimeRequirement
    department: Science
    time: 36000 #10 hrs
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  supervisors: job-supervisors-captain
  canBeAntag: true # Sunrise-Edit
  radioBold: true # Sunrise-Edit
  displayWeight: 50 # Sunrise-Edit
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant, DeathRattleImplantBlueShield ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  speciesBlacklist:
  - Vox # Sunrise-Edit

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    pocket1: HandheldRoboAnalyzer # Sunrise-Edit
    pocket2: Nanopaste10 # Sunrise-Edit
    ears: ClothingHeadsetRD
  storage:
    back:
    - Flash
    - Telebaton # Sunrise-Edit
