- type: antag
  id: SpaceNinja
  name: roles-antag-space-ninja-name
  antagonist: true
  setPreference: false
  playTimeTracker: AntagNinja # Sunrise-Edit
  objective: roles-antag-space-ninja-objective
  guides: [ SpaceNinja ]

#Ninja Gear
- type: startingGear
  id: SpaceNinjaGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNinja
    back: ClothingBackpackSatchel
    mask: ClothingMaskNinja
    head: ClothingHeadHelmetSpaceNinja
    eyes: ClothingEyesVisorNinja
    gloves: ClothingHandsGlovesSpaceNinja
    outerClothing: ClothingOuterSuitSpaceNinja
    shoes: ClothingShoesSpaceNinjaBiocode # Sunrise-Edit
    id: AgentIDCard
    ears: ClothingHeadsetNinja
    pocket1: SpiderCharge
    pocket2: HandHeldMassScanner
    belt: EnergyKatana
  inhand:
    - JetpackBlackFilled
  storage:
    back: # belt holds katana so satchel has the tools for sabotaging things
    - Crowbar
    - Wrench
    - Screwdriver
    - Wirecutter
    - Welder
    - Multitool

- type: chameleonOutfit
  id: NinjaChameleonOutfit
  name: roles-antag-space-ninja-name
  startingGear: SpaceNinjaGear
  equipment:
    id: PassengerPDA
    neck: ClothingNeckGoldmedal
