name: Publish Stable

concurrency:
  group: publish-mapping
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fail if we are attempting to run on the master branch
      if: ${{GITHUB.REF_NAME == 'master'}}
      run: exit 1

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: actions/checkout@v4.2.2
      with:
        submodules: 'recursive'

    - name: Checkout SunrisePrivate
      uses: actions/checkout@v4.2.2
      with:
        repository: ${{ secrets.SUNRISE_PRIVATE_REPO }}
        path: SunrisePrivate
        ssh-key: ${{ secrets.SUNRISE_PRIVATE_REPO_SSH_KEY }}

    - name: Move Sunrise Private files
      run: python3 Tools/_sunrise/move_private.py --clone-dir "SunrisePrivate" --target-dirs "Resources" "Content.Client" "Content.Server" "Content.Shared"

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 9.0.x

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform win-x64 --platform linux-x64 --platform osx-x64 --platform linux-arm64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    - name: Publish version
      run: Tools/publish_multi_request.py --fork-id sunrise_station_stable
      env:
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        GITHUB_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}

    - name: Publish discord changelog (SUNRISE)
      run: Tools/_sunrise/actions_changelogs_since_last_run.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISCORD_WEBHOOK_URL: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK_SUNRISE }}

    - name: Publish discord changelog (LUST)
      continue-on-error: true
      run: Tools/_sunrise/actions_changelogs_since_last_run.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISCORD_WEBHOOK_URL: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK_LUST }}

    - name: Publish discord changelog (FISH)
      continue-on-error: true
      run: Tools/_sunrise/actions_changelogs_since_last_run.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DISCORD_WEBHOOK_URL: ${{ secrets.CHANGELOG_DISCORD_WEBHOOK_FISH }}
